'use client'
import Sidebar from "@/components/layout/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import { useAuthContext } from "@/context/Context";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


    const { user, loading } = useAuthContext();
    const router = useRouter();

    useEffect(() => {
      if (!loading) {
        const token = typeof window !== 'undefined' ? localStorage.getItem('access_token') : null;
       
        if (!token) {
          router.replace('/login');
        }
      }
    }, [loading, router]);
  return (
    <div className="flex">
      <Sidebar />
      <main className="flex-1 bg-[#eef7ff] min-h-screen">
        <Navbar />
        {children}
      </main>
    </div>
  );
}